# Generated by Django 2.1.3 on 2018-11-28 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.FileField(default=datetime.datetime(2018, 11, 28, 12, 51, 25, 433135, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
